tilltue/TLPhotoPicker

- TLPhotoPicker/Classes/TLPhotosPickerViewController.swift
시뮬레이터로 돌렸을 때, 컬렉션뷰 첫번째에 있는 카메라 셀을 터치하면 크래시가 발생합니다.
그 대신 로그를 찍도록 변경해봤습니다.
> 시뮬레이터에서 카메라 버튼 누르면 크래시 나는 현상 수정

- TLPhotoPicker/Classes/TLPhotosPickerViewController.swift
IPhone 5 When iOS 10.3.1 uses the camera to take pictures
The app crashes because the dismiss method is not running on the main thread.
/*
아이폰5 iOS 10.3.1에서 카메라를 사용하여 사진을 찍어 사용하는 경우 
dismiss 메소드가 메인쓰레드에서 실행되지 않아 앱이 크래쉬 됩니다. 
*/
> :bug: carsh on iPhone 5 when taking pictures with the camera

- TLPhotoPicker.podspec
This will still work if the other apps are building with Swift 3.2, since those versions can co-exist between projects.
> Enforce Swift 4 usage in the podspec.

- TLPhotoPicker.podspec
Cocoapods 1.4.0 adds support for setting the Swift version used by a pod. This should fix the problems with the SWIFT_VERSION field not actually being applied when building.
> Add new swift_version parameter to podspec

- Example/TLPhotoPicker/ViewController.swift
- README.md
- TLPhotoPicker/Classes/TLPhotosPickerViewController.swift
I wasn't 100% sure of the best name for the delegate/block, but the feature works as expected and allows the implementing app to perform some handling (such as showing an alert) of the cases where camera permissions have been denied.
> Add support for delegate/block-based handling of no camera permissions

- TLPhotoPicker/Classes/TLBundle.swift
- TLPhotoPicker/Classes/TLPhotoLibrary.swift
When you set the maxVideoDuration, like 30 seconds, it works on initial loading. But if you change album and go back to the camera roll, you can see the videos that are longer than 30 seconds.
Also, the number of media on the album does not match with the exact number of media when maxVideoDuration is set.
> Fixed predicate inconsistency problem when maxVideoDuration is set

- TLPhotoPicker/Classes/TLPhotosPickerViewController.swift
When denied the controller dismisses and if originally denied there's no dismiss line. So it's tricky to dimiss the view controller in the handleNoAlbumAuthorization delegate method.
And it's possible for user to customize the PhotosPickerViewController to show some other views without dismissing on default case.
> on #96. To unify handling of no album authorization.

- TLPhotoPicker/Classes/TLPhotosPickerViewController.swift
I tried to collect logs by customizing the TLPhotosPickerViewController.
But because focusedCollection and collections properties are private, I cannot differentiate whether user selected camera cell, selected cell or deselected cell. And I also cannot get information on collection when user tapped a album because of same reason.
I think others also need to collect logs on the user event.
I will be so grateful if I can collect the logs on user events.
> added delegate functions to collect logs of user events

- TLPhotoPicker/Classes/TLPhotosPickerViewController.swift
Fixes a crash: Fatal Exception: NSInternalInconsistencyException attempt to delete and reload the same index path
For reference:
https://stackoverflow.com/questions/29337765/crash-attempt-to-delete-and-reload-the-same-index-path/35799537#35799537
> These indexes are relative to the original fetch result (the fetchResultBeforeChanges property) after you’ve applied the changes described by the removedIndexes and insertedIndexes properties; when updating your app’s interface, **apply changes after removals and insertions and before moves.**
> Fix crash while reloading photo library

- TLPhotoPicker/Classes/TLPhotoLibrary.swift
```
configure.allowedVideo = false
configure.allowedLivePhotos = false
```
```
<PHFetchOptions: 0x10bee75f0> predicate=mediaType != 2 AND (mediaType == 2 OR mediaSubtype != 8), sort=(
"(creationDate, descending, compare:)"
), wantsChangeDetails=1
```
```
<PHFetchOptions: 0x101e40a10> predicate=mediaType != 2 AND (NOT mediaSubtype & 8 != 0), sort=(
"(creationDate, descending, compare:)"
), wantsChangeDetails=1
```
> Fix wrong predicate for allowedLivePhotos option

- TLPhotoPicker/Classes/TLAlbumPopView.swift
- TLPhotoPicker/Classes/TLCollectionTableViewCell.swift
- TLPhotoPicker/Classes/TLCollectionTableViewCell.xib
- TLPhotoPicker/Classes/TLPhotosPickerViewController.xib
Since #219 has been an issue for a while, I'm gonna fix it myself :)
A few notes:
- I removed the 10px margin on the tableview cell and applied it to the thumbnail. I think it makes more sense this way.
- The `systemBackground` color is adaptive. There's no need to check for dark mode like what you did I think. Just use it and it will be white/black as appropriate.
- **The navbar is still broken: if you open the photo picker and then switch to the opposite appearance, the navbar background doesn't adapt to the change.** I actually didn't realize it before, but when I'm validating my change using your sample project I saw this bug. It's most likely you aren't using an adaptive color for the navbar background, but I couldn't find where you set it. Can you fix this?
Thank you!
> Fix iOS 13 white margin in dark mode

- TLPhotoPicker/Classes/TLPhotoCollectionViewCell.swift
- TLPhotoPicker/Classes/TLPhotosPickerViewController.swift
- TLPhotoPicker/TLPhotoPicker.xcodeproj/project.pbxproj
- TLPhotoPicker/TLPhotoPicker/TLAssetPreviewViewController.swift
Adds long press preview to images.
This PR adds support for long press previews of photos/videos. 
On iOS versions <13.0 it only shows a preview of the selected asset, while on iOS 13+ it also adds a contextual menu with the option to select/deselect the previewed photo. 
The previews support static photos, live photos and videos. 
In order to achieve this, a new read-only property was added to `TLPhotoCollectionViewCell`: 
`open internal(set) var asset: PHAsset?` as well as 2 delegate callbacks to `TLPhotosPickerViewController`. 
`public func previewingContext(_ previewingContext: UIViewControllerPreviewing, viewControllerForLocation location: CGPoint) -> UIViewController?` is used for iOS <13 devices and only shows a preview of the photo on a force touch. 
`public func collectionView(_ …
> Add long press preview for images

- Example/Pods/Pods.xcodeproj/project.pbxproj
The file "TLAssetPreviewViewController" was missing in _Pod.xcodeproj that caused carthage build to fail.
> Fixed Carthage build issue

- TLPhotoPicker/Classes/TLPhotoCollectionViewCell.swift
I think it's more logical to hide the orderBgView and orderLabel while the singleSelectedMode is true.
> Hide orderBgView and orderLabel when singleSelectedMode is true

- TLPhotoPicker/Classes/TLPhotosPickerViewController.swift
changed access modifiers from public to open so subclasses can override collection view layout delegate methods.
> change access levels for UICollectionViewDelegateFlowLayout

- TLPhotoPicker/Classes/TLPhotosPickerViewController.swift
There is a layout issue about number of column for iPhone 12 ( In case of iPhone12, It displays 2 number of column, not standard 3 )
At first, I expected calculation issue, but it seems fine and it fits with iPhone12 390 width ( 3 items(380) + 10 spacing(5,5))
I think it's bug or floating point issue or something. MinimumInteritemSpacing is set to 5, and with some reason, 3 items width calculation is more than 380. As a result, collectionView layout make its column number to 2 in order to conform minimumInteritemSpacing value ( 5 ).
And what I suggest is that column number of 3 should be preserved by **changing minimumInteritemSpacing value**. 
Because even though margin of error for item size calculation exists, it is too small to make problem **if we guarantee 3 number of column even …
> Fixed Critical iPhone12 layout issue

- TLPhotoPicker/Classes/TLPhotosPickerViewController.swift
in iOS 15 the done button and cancel appear with clear color .. here I just add blue color for the two buttons
> fix_done_and_cancle_btn_colors_in_ios15

- TLPhotoPicker/Classes/TLPhotosPickerViewController.swift
Reset `thumbnailSize` when detect changed device orientation so it could be calculated again to fit the new view width
> Reset thumbnailSize to allow updating the item size when change the device orientation

- TLPhotoPicker/Classes/TLAssetsCollection.swift
Change the `init` for `TLPHAsset` from private to public. This allows for more customizability, such as being able to launch `TLPhotoPicker` with already selected `PHAssets` from another source.
> Make init for TLPHAsset public.

- TLPhotoPicker/Classes/TLAssetsCollection.swift
- TLPhotoPicker/Classes/TLPhotosPickerViewController.swift
This change is needed to properly display the empty image when all albums are empty. Currently the camera button counts as an items and the empty state does not show.
> Fix for empty state

- TLPhotoPicker/Classes/TLPhotosPickerViewController.swift
> Fix "Cannot find 'TARGET_OS_SIMULATOR' in scope" error in Xcode 16.3.
